import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";

const fontSans = FontSans({ subsets: ["latin"],variable: "--font-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased flex items-start justify-between",
          fontSans.variable
        )}>
          <div className="hidden lg:flex min-w-[300px] min-h-screen">
            <Sidebar />
          </div>
          
          <main className="w-full h-full grid">
            <Header />
            <div className="p-8">
              {children}
            </div>
          </main>
        </body>
    </html>
  );
}
